let relics = [
    {
        name: `Agni's Sparkler`,
        img: 'Agnis_Sparkler.png',
        cost: 175,
        description: 'Doubles the damage of burn you inflict',
    },
    {
        name: `Amulet of Sundering`,
        img: 'Amulet_of_Sundering.png',
        cost: 150,
        description: '',
    },
    {
        name: `Analytical Monocle`,
        img: 'Analytical_Monocle.png',
        cost: 150,
        description: '',
    },
    {
        name: `Ancient Fountain Pen`,
        img: 'Ancient_Fountain_Pen.png',
        cost: 150,
        description: '',
    },
    {
        name: `Assassin's Blade`,
        img: 'Assassins_Blade.png',
        cost: 150,
        description: '',
    },
    {
        name: `Auditor's Talisman`,
        img: 'Auditors_Talisman.png',
        cost: 175,
        description: '',
    },
    {
        name: `Autograph Pad`,
        img: 'Autograph_Pad.png',
        cost: 125,
        description: '',
    },
    {
        name: `Battery of Taranis`,
        img: 'Battery_of_Taranis.png',
        cost: 150,
        description: '',
    },
    {
        name: `Berserker's Axe`,
        img: 'Berserkers_Axe.png',
        cost: 150,
        description: '',
    },
    {
        name: `Berserker's Helm`,
        img: 'Berserkers_Helm.png',
        cost: 150,
        description: '',
    },
    {
        name: `Boots of Celerity`,
        img: 'Boots_of_Celerity.png',
        cost: 150,
        description: '',
    },
    {
        name: `Cabi's Bubble Gum`,
        img: 'Cabis_Bubble_Gum.png',
        cost: 100,
        description: '',
    },
    {
        name: `Cabi's Cinnamon Hots`,
        img: 'Cabis_Cinnamon_Hots.png',
        cost: 100,
        description: '',
    },
    {
        name: `Cabi's Citrus Sweets`,
        img: 'Cabis_Citrus_Sweets.png',
        cost: 100,
        description: '',
    },
    {
        name: `Cabi's Cotton Candy`,
        img: 'Cabis_Cotton_Candy.png',
        cost: 100,
        description: '',
    },
    {
        name: `Cabi's Raw Chocolate`,
        img: 'Cabis_Raw_Chocolate.png',
        cost: 100,
        description: '',
    },
    {
        name: `Captain's Ring`,
        img: 'Captains_Ring.png',
        cost: 150,
        description: '',
    },
    {
        name: `Cartographer's Quill`,
        img: 'Cartographers_Quill.png',
        cost: 175,
        description: '',
    },
    {
        name: `Chaos Scanner`,
        img: 'Chaos_Scanner.png',
        cost: 150,
        description: '',
    },
    {
        name: `Chaos Visor`,
        img: 'Chaos_Visor.png',
        cost: 125,
        description: '',
    },
    {
        name: `Claws of Tomo`,
        img: 'Claws_of_Tomo.png',
        cost: 75,
        description: '',
    },
    {
        name: `Cobalt Firestone`,
        img: 'Cobalt_Firestone.png',
        cost: 150,
        description: '',
    },
    {
        name: `Covert Ops Mask`,
        img: 'Covert_Ops_Mask.png',
        cost: 150,
        description: '',
    },
    {
        name: `Curse Eater's Mask`,
        img: 'Curse_Eaters_Mask.png',
        cost: 150,
        description: '',
    },
    {
        name: `Dagger of Midas`,
        img: 'Dagger_of_Midas.png',
        cost: 150,
        description: '',
    },
    {
        name: `Dark Katana`,
        img: 'Dark_Katana.png',
        cost: 175,
        description: '',
    },
    {
        name: `Devi's Bug Spray`,
        img: 'Devis_Bug_Spray.png',
        cost: 175,
        description: '',
    },
    {
        name: `Dice of the Nemesis`,
        img: 'Dice_of_the_Nemesis.png',
        cost: 150,
        description: '',
    },
    {
        name: `Ebon Wolf's Cloak`,
        img: 'Ebon_Wolfs_Cloak.png',
        cost: 150,
        description: '',
    },
    {
        name: `Electrifying Smock`,
        img: 'Electrifying_Smock.png',
        cost: 150,
        description: '',
    },
    {
        name: `Fiery Paintbrush`,
        img: 'Fiery_Paintbrush.png',
        cost: 150,
        description: '',
    },
    {
        name: `Fortune Cookie`,
        img: 'Fortune_Cookie.png',
        cost: 150,
        description: '',
    },
    {
        name: `Gaia's Shovel`,
        img: 'Gaias_Shovel.png',
        cost: 150,
        description: '',
    },
    {
        name: `Gloves of Gambit`,
        img: 'Gloves_of_Gambit.png',
        cost: 175,
        description: '',
    },
    {
        name: `Hunter's Stiletto`,
        img: 'Hunters_Stiletto.png',
        cost: 150,
        description: '',
    },
    {
        name: `Idealist's Mirror`,
        img: 'Idealists_Mirror.png',
        cost: 300,
        description: '',
    },
    {
        name: `Idealist's Scorecard`,
        img: 'Idealists_Scorecard.png',
        cost: 300,
        description: '',
    },
    {
        name: `Idealist's Vest`,
        img: 'Idealists_Vest.png',
        cost: 300,
        description: '',
    },
    {
        name: `Ifrit's Matchstick`,
        img: 'Ifrits_Matchstick.png',
        cost: 150,
        description: '',
    },
    {
        name: `Indra's Copper Pipe`,
        img: 'Indras_Copper_Pipe.png',
        cost: 175,
        description: '',
    },
    {
        name: `Jade's Jeweled Tiara`,
        img: 'Jades_Jeweled_Tiara.png',
        cost: 125,
        description: '',
    },
    {
        name: `Lotus Froststone`,
        img: 'Lotus_Froststone.png',
        cost: 150,
        description: '',
    },
    {
        name: `Magician's Top Hat`,
        img: 'Magicians_Top_Hat.png',
        cost: 150,
        description: '',
    },
    {
        name: `Megalodon Tooth`,
        img: 'Megalodon_Tooth.png',
        cost: 150,
        description: '',
    },
    {
        name: `Merchant's Cart`,
        img: 'Merchants_Cart.png',
        cost: 150,
        description: '',
    },
    {
        name: `Nerite Shell`,
        img: 'Nerite_Shell.png',
        cost: 125,
        description: '',
    },
    {
        name: `Neve's Citrine`,
        img: 'Neves_Citrine.png',
        cost: 250,
        description: '',
    },
    {
        name: `Neve's Ruby`,
        img: 'Neves_Ruby.png',
        cost: 250,
        description: '',
    },
    {
        name: `Noxious Dappercap`,
        img: 'Noxious_Dappercap.png',
        cost: 125,
        description: '',
    },
    {
        name: `Pandemic Pouch`,
        img: 'Pandemic_Pouch.png',
        cost: 150,
        description: '',
    },
    {
        name: `Paralytic Venomstone`,
        img: 'Paralytic_Venomstone.png',
        cost: 150,
        description: '',
    },
    {
        name: `Permafrost Cube`,
        img: 'Permafrost_Cube.png',
        cost: 125,
        description: '',
    },
    {
        name: `Phoenix Talon`,
        img: 'Phoenix_Talon.png',
        cost: 125,
        description: '',
    },
    {
        name: `Royal Flush`,
        img: 'Royal_Flush.png',
        cost: 150,
        description: '',
    },
    {
        name: `Rudra's Pinwheel`,
        img: 'Rudras_Pinwheel.png',
        cost: 150,
        description: '',
    },
    {
        name: `Secret Wild Card`,
        img: 'Secret_Wild_Card.png',
        cost: 175,
        description: '',
    },
    {
        name: `Shark Mask`,
        img: 'Shark_Mask.png',
        cost: 175,
        description: '',
    },
    {
        name: `Shiva's Water Bottle`,
        img: 'Shivas_Water_Bottle.png',
        cost: 150,
        description: '',
    },
    {
        name: `Sidewinder's Badge`,
        img: 'Sidewinders_Badge.png',
        cost: 175,
        description: '',
    },
    {
        name: `Singing Bowl`,
        img: 'Singing_Bowl.png',
        cost: 175,
        description: '',
    },
    {
        name: `Sinister Ledger`,
        img: 'Sinister_Ledger.png',
        cost: 150,
        description: '',
    },
    {
        name: `Sleepy Thunderstone`,
        img: 'Sleepy_Thunderstone.png',
        cost: 150,
        description: '',
    },
    {
        name: `Soccer Cleats`,
        img: 'Soccer_Cleats.png',
        cost: 150,
        description: '',
    },
    {
        name: `Sparrow Windstone`,
        img: 'Sparrow_Windstone.png',
        cost: 150,
        description: '',
    },
    {
        name: `Special Snowflake`,
        img: 'Special_Snowflake.png',
        cost: 125,
        description: '',
    },
    {
        name: `Stanza of Frost`,
        img: 'Stanza_of_Frost.png',
        cost: 150,
        description: '',
    },
    {
        name: `Tapping Gloves`,
        img: 'Tapping_Gloves.png',
        cost: 175,
        description: '',
    },
    {
        name: `Tesla Coil`,
        img: 'Tesla_Coil.png',
        cost: 125,
        description: '',
    },
    {
        name: `Vicious Bunny Ears`,
        img: 'Vicious_Bunny_Ears.png',
        cost: 125,
        description: '',
    },
    {
        name: `Wanderer's Mechanism`,
        img: 'Wanderers_Mechanism.png',
        cost: 175,
        description: '',
    },
    {
        name: `Whimsical Explodium`,
        img: 'Whimsical_Explodium.png',
        cost: 125,
        description: '',
    },
    {
        name: `Absorption Coil`,
        img: 'Absorption_Coil.png',
        cost: 125,
        description: '',
    },
    {
        name: `Albert's Formula`,
        img: 'Alberts_Formula.png',
        cost: 125,
        description: '',
    },
    {
        name: `Amethyst Key`,
        img: 'Amethyst_Key.png',
        cost: 100,
        description: '',
    },
    {
        name: `Arcana Rewards Card`,
        img: 'Arcana_Rewards_Card.png',
        cost: 100,
        description: '',
    },
    {
        name: `Archaic Cheat Sheet`,
        img: 'Archaic_Cheat_Sheet.png',
        cost: 150,
        description: '',
    },
    {
        name: `Bladed Buckler`,
        img: 'Bladed_Buckler.png',
        cost: 175,
        description: '',
    },
    {
        name: `Blasting Sprite Aura`,
        img: 'Blasting_Sprite_Aura.png',
        cost: 125,
        description: '',
    },
    {
        name: `Boots of Frenzy`,
        img: 'Boots_of_Frenzy.png',
        cost: 150,
        description: '',
    },
    {
        name: `Bounty Hunter's Seal`,
        img: 'Bounty_Hunters_Seal.png',
        cost: 100,
        description: '',
    },
    {
        name: `C-99 Piggy Bank`,
        img: 'C-99_Piggy_Bank.png',
        cost: 150,
        description: '',
    },
    {
        name: `Chrono Glove`,
        img: 'Chrono_Glove.png',
        cost: 125,
        description: '',
    },
    {
        name: `Combo Gloves`,
        img: 'Combo_Gloves.png',
        cost: 150,
        description: '',
    },
    {
        name: `Conqueror's Belt`,
        img: 'Conquerors_Belt.png',
        cost: 150,
        description: '',
    },
    {
        name: `Conqueror's Cloak`,
        img: 'Conquerors_Cloak.png',
        cost: 150,
        description: '',
    },
    {
        name: `Conqueror's Helmet`,
        img: 'Conquerors_Helmet.png',
        cost: 150,
        description: '',
    },
    {
        name: `Curse Eater's Watch`,
        img: 'Curse_Eaters_Watch.png',
        cost: 125,
        description: '',
    },
    {
        name: `Dated Sunglasses`,
        img: 'Dated_Sunglasses.png',
        cost: 150,
        description: '',
    },
    {
        name: `Demi's Teapot`,
        img: 'Demis_Teapot.png',
        cost: 175,
        description: '',
    },
    {
        name: `Destructive Abacus`,
        img: 'Destructive_Abacus.png',
        cost: 150,
        description: '',
    },
    {
        name: `Elemental Pointes`,
        img: 'Elemental_Pointes.png',
        cost: 150,
        description: '',
    },
    {
        name: `Emerald Key`,
        img: 'Emerald_Key.png',
        cost: 100,
        description: '',
    },
    {
        name: `Evening Gloves`,
        img: 'Evening_Gloves.png',
        cost: 150,
        description: '',
    },
    {
        name: `Family Seal`,
        img: 'Family_Seal.png',
        cost: 150,
        description: '',
    },
    {
        name: `Flak Gauntlet`,
        img: 'Flak_Gauntlet.png',
        cost: 150,
        description: '',
    },
    {
        name: `Freezing Sprite Naya`,
        img: 'Freezing_Sprite_Naya.png',
        cost: 125,
        description: '',
    },
    {
        name: `Glove of Midas`,
        img: 'Glove_of_Midas.png',
        cost: 125,
        description: '',
    },
    {
        name: `Graduation Cap`,
        img: 'Graduation_Cap.png',
        cost: 125,
        description: '',
    },
    {
        name: `Grimoire of Ruin`,
        img: 'Grimoire_of_Ruin.png',
        cost: 175,
        description: '',
    },
    {
        name: `Gyroscopic Inkwell`,
        img: 'Gyroscopic_Inkwell.png',
        cost: 175,
        description: '',
    },
    {
        name: `Hardcover Textbook`,
        img: 'Hardcover_Textbook.png',
        cost: 125,
        description: '',
    },
    {
        name: `Hyperbolic Train`,
        img: 'Hyperbolic_Train.png',
        cost: 150,
        description: '',
    },
    {
        name: `Igniting Sprite Vesa`,
        img: 'Igniting_Sprite_Vesa.png',
        cost: 150,
        description: '',
    },
    {
        name: `Infinity Marble`,
        img: 'Infinity_Marble.png',
        cost: 150,
        description: '',
    },
    {
        name: `Jade's Gem Locator`,
        img: 'Jades_Gem_Locator.png',
        cost: 125,
        description: '',
    },
    {
        name: `Journal of Midas`,
        img: 'Journal_of_Midas.png',
        cost: 125,
        description: '',
    },
    {
        name: `Jumper Cables`,
        img: 'Jumper_Cables.png',
        cost: 150,
        description: '',
    },
    {
        name: `Mobius Quill`,
        img: 'Mobius_Quill.png',
        cost: 150,
        description: '',
    },
    {
        name: `Mystic Monopole`,
        img: 'Mystic_Monopole.png',
        cost: 150,
        description: '',
    },
    {
        name: `Neve's Sapphire`,
        img: 'Neves_Sapphire.png',
        cost: 250,
        description: '',
    },
    {
        name: `Nocturnal Sundial`,
        img: 'Nocturnal_Sundial.png',
        cost: 150,
        description: '',
    },
    {
        name: `Pathfinder's Map`,
        img: 'Pathfinders_Map.png',
        cost: 175,
        description: '',
    },
    {
        name: `Phyyrnx's Hourglass`,
        img: 'Phyyrnxs_Hourglass.png',
        cost: 175,
        description: '',
    },
    {
        name: `Plaguing Sprite Dria`,
        img: 'Plaguing_Sprite_Dria.png',
        cost: 150,
        description: '',
    },
    {
        name: `Pop-up Primer`,
        img: 'Pop-up_Primer.png',
        cost: 200,
        description: '',
    },
    {
        name: `Raffle Ticket`,
        img: 'Raffle_Ticket.png',
        cost: 200,
        description: '',
    },
    {
        name: `Reinforced Bracers`,
        img: 'Reinforced_Bracers.png',
        cost: 200,
        description: '',
    },
    {
        name: `Relic Rewards Card`,
        img: 'Relic_Rewards_Card.png',
        cost: 100,
        description: 'All gold costs for relics are discounted! (20%)',
    },
    {
        name: `Ring of Reserves`,
        img: 'Ring_of_Reserves.png',
        cost: 175,
        description: '',
    },
    {
        name: `Roxel's Pendulum`,
        img: 'Roxels_Pendulum.png',
        cost: 125,
        description: '',
    },
    {
        name: `Ruby Key`,
        img: 'Ruby_Key.png',
        cost: 100,
        description: '',
    },
    {
        name: `Sparking Sprite Etra`,
        img: 'Sparking_Sprite_Etra.png',
        cost: 175,
        description: '',
    },
    {
        name: `Spice Rack`,
        img: 'Spice_Rack.png',
        cost: 150,
        description: '',
    },
    {
        name: `Supply Crate`,
        img: 'Supply_Crate.png',
        cost: 100,
        description: '',
    },
    {
        name: `Surefire Rocket`,
        img: 'Surefire_Rocket.png',
        cost: 175,
        description: '',
    },
    {
        name: `Tears of Midas`,
        img: 'Tears_of_Midas.png',
        cost: 125,
        description: '',
    },
    {
        name: `Tozy's Pocket Watch`,
        img: 'Tozys_Pocket_Watch.png',
        cost: 175,
        description: '',
    },
    {
        name: `Unicorn Tail`,
        img: 'Unicorn_Tail.png',
        cost: 100,
        description: '',
    },
    {
        name: `Vampire's Cookbook`,
        img: 'Vampires_Cookbook.png',
        cost: 175,
        description: '',
    },
    {
        name: `Wallet of Vigor`,
        img: 'Wallet_of_Vigor.png',
        cost: 100,
        description: '',
    },
    {
        name: `Watercolor Palette`,
        img: 'Watercolor_Palette.png',
        cost: 150,
        description: '',
    },
    {
        name: `Yuna's Storybook`,
        img: 'Yunas_Storybook.png',
        cost: 175,
        description: '',
    },
    {
        name: `Antiquated Tabi`,
        img: 'Antiquated_Tabi.png',
        cost: 125,
        description: '',
    },
    {
        name: `Armor of Resolve`,
        img: 'Armor_of_Resolve.png',
        cost: 150,
        description: '',
    },
    {
        name: `Auger of Poetry`,
        img: 'Auger_of_Poetry.png',
        cost: 125,
        description: '',
    },
    {
        name: `Bach's Escape Key`,
        img: 'Bachs_Escape_Key.png',
        cost: 175,
        description: '',
    },
    {
        name: `Blades of Sympathy`,
        img: 'Blades_of_Sympathy.png',
        cost: 150,
        description: '',
    },
    {
        name: `Bracers of the Beast`,
        img: 'Bracers_of_the_Beast.png',
        cost: 150,
        description: '',
    },
    {
        name: `Breezy Gray Canvas`,
        img: 'Breezy_Gray_Canvas.png',
        cost: 150,
        description: '',
    },
    {
        name: `Brilliant Balloon`,
        img: 'Brilliant_Balloon.png',
        cost: 150,
        description: '',
    },
    {
        name: `Calcifying Bonemail`,
        img: 'Calcifying_Bonemail.png',
        cost: 150,
        description: '',
    },
    {
        name: `Calvin's Sandy Shoes`,
        img: 'Calvins_Sandy_Shoes.png',
        cost: 175,
        description: '',
    },
    {
        name: `Cassim's Airy Cloak`,
        img: 'Cassims_Airy_Cloak.png',
        cost: 175,
        description: '',
    },
    {
        name: `Charming Teddy Bear`,
        img: 'Charming_Teddy_Bear.png',
        cost: 150,
        description: '',
    },
    {
        name: `Curse Eater's Vest`,
        img: 'Curse_Eaters_Vest.png',
        cost: 150,
        description: '',
    },
    {
        name: `Cushioned Flip-flops`,
        img: 'Cushioned_Flip-flops.png',
        cost: 200,
        description: '',
    },
    {
        name: `Deafening Cymbals`,
        img: 'Deafening_Cymbals.png',
        cost: 150,
        description: '',
    },
    {
        name: `Ella's Glass Kite`,
        img: 'Ellas_Glass_Kite.png',
        cost: 125,
        description: '',
    },
    {
        name: `Elven Ears`,
        img: 'Elven_Ears.png',
        cost: 125,
        description: '',
    },
    {
        name: `Equestricap`,
        img: 'Equestricap.png',
        cost: 150,
        description: '',
    },
    {
        name: `Euphie's Shawl`,
        img: 'Euphies_Shawl.png',
        cost: 125,
        description: '',
    },
    {
        name: `Firstborn's Gauntlet`,
        img: 'Firstborns_Gauntlet.png',
        cost: 150,
        description: '',
    },
    {
        name: `Flashy Windbreaker`,
        img: 'Flashy_Windbreaker.png',
        cost: 125,
        description: '',
    },
    {
        name: `Fuzzy Handwarmers`,
        img: 'Fuzzy_Handwarmers.png',
        cost: 125,
        description: '',
    },
    {
        name: `Giant's Heart`,
        img: 'Giants_Heart.png',
        cost: 125,
        description: '',
    },
    {
        name: `Greased Boots`,
        img: 'Greased_Boots.png',
        cost: 150,
        description: '',
    },
    {
        name: `Gummy Vitamins`,
        img: 'Gummy_Vitamins.png',
        cost: 125,
        description: '',
    },
    {
        name: `Heavy Travel Jacket`,
        img: 'Heavy_Travel_Jacket.png',
        cost: 150,
        description: '',
    },
    {
        name: `Helm of Midas`,
        img: 'Helm_of_Midas.png',
        cost: 150,
        description: '',
    },
    {
        name: `Hummingbird Feather`,
        img: 'Hummingbird_Feather.png',
        cost: 150,
        description: '',
    },
    {
        name: `Insulated Vest`,
        img: 'Insulated_Vest.png',
        cost: 125,
        description: '',
    },
    {
        name: `Ironclad Cardholder`,
        img: 'Ironclad_Cardholder.png',
        cost: 175,
        description: '',
    },
    {
        name: `Jade's Chakra Locket`,
        img: 'Jades_Chakra_Locket.png',
        cost: 125,
        description: '',
    },
    {
        name: `Jewelry Box`,
        img: 'Jewelry_Box.png',
        cost: 200,
        description: '',
    },
    {
        name: `Kali's Flower Diadem`,
        img: 'Kalis_Flower_Diadem.png',
        cost: 225,
        description: '',
    },
    {
        name: `Leemo's Leaf`,
        img: 'Leemos_Leaf.png',
        cost: 200,
        description: '',
    },
    {
        name: `Lei's Drum`,
        img: 'Leis_Drum.png',
        cost: 150,
        description: '',
    },
    {
        name: `Limited Edition Robe`,
        img: 'Limited_Edition_Robe.png',
        cost: 175,
        description: '',
    },
    {
        name: `Memory Chainmail`,
        img: 'Memory_Chainmail.png',
        cost: 150,
        description: '',
    },
    {
        name: `Mercury's Sandals`,
        img: 'Mercurys_Sandals.png',
        cost: 125,
        description: '',
    },
    {
        name: `Mirror Shield`,
        img: 'Mirror_Shield.png',
        cost: 150,
        description: '',
    },
    {
        name: `Neve's Emerald`,
        img: 'Neves_Emerald.png',
        cost: 250,
        description: '',
    },
    {
        name: `Neve's Quartz`,
        img: 'Neves_Quartz.png',
        cost: 250,
        description: '',
    },
    {
        name: `Pathfinder's Knapsack`,
        img: 'Pathfinders_Knapsack.png',
        cost: 200,
        description: '',
    },
    {
        name: `Pazu's Favorite Hat`,
        img: 'Pazus_Favorite_Hat.png',
        cost: 250,
        description: '',
    },
    {
        name: `Prismatic Vambrace`,
        img: 'Prismatic_Vambrace.png',
        cost: 150,
        description: '',
    },
    {
        name: `Prismatic Windchime`,
        img: 'Prismatic_Windchime.png',
        cost: 150,
        description: '',
    },
    {
        name: `Puffy Parka`,
        img: 'Puffy_Parka.png',
        cost: 125,
        description: '',
    },
    {
        name: `Raspberry Cookie Box`,
        img: 'Raspberry_Cookie_Box.png',
        cost: 150,
        description: '',
    },
    {
        name: `Reactive Vinemail`,
        img: 'Reactive_Vinemail.png',
        cost: 150,
        description: '',
    },
    {
        name: `Regenerative Inkwell`,
        img: 'Regenerative_Inkwell.png',
        cost: 200,
        description: '',
    },
    {
        name: `Reliable Backpack`,
        img: 'Reliable_Backpack.png',
        cost: 150,
        description: '',
    },
    {
        name: `Resolute Svalinn`,
        img: 'Resolute_Svalinn.png',
        cost: 125,
        description: '',
    },
    {
        name: `Ring of Recycling`,
        img: 'Ring_of_Recycling.png',
        cost: 175,
        description: '',
    },
    {
        name: `Royal Jelly`,
        img: 'Royal_Jelly.png',
        cost: 125,
        description: `Healing potions no longer decrease in effectiveness everytime they're used!`,
    },
    {
        name: `Rubber Raincoat`,
        img: 'Rubber_Raincoat.png',
        cost: 125,
        description: '',
    },
    {
        name: `Sano's Headband`,
        img: 'Sanos_Headband.png',
        cost: 125,
        description: '',
    },
    {
        name: `Scissors of Vitality`,
        img: 'Scissors_of_Vitality.png',
        cost: 200,
        description: '',
    },
    {
        name: `Spell Thief's Socks`,
        img: 'Spell_Thiefs_Socks.png',
        cost: 150,
        description: '',
    },
    {
        name: `Starchy Parachute`,
        img: 'Starchy_Parachute.png',
        cost: 125,
        description: '',
    },
    {
        name: `Sturdy Shoebox`,
        img: 'Sturdy_Shoebox.png',
        cost: 150,
        description: '',
    },
    {
        name: `Sturdy Wooden Easel`,
        img: 'Sturdy_Wooden_Easel.png',
        cost: 150,
        description: '',
    },
    {
        name: `Stygian Turtle Shell`,
        img: 'Stygian_Turtle_Shell.png',
        cost: 175,
        description: '',
    },
    {
        name: `Super Carrot Cake`,
        img: 'Super_Carrot_Cake.png',
        cost: 150,
        description: '',
    },
    {
        name: `Super Sunscreen`,
        img: 'Super_Sunscreen.png',
        cost: 125,
        description: '',
    },
    {
        name: `Takeout Box`,
        img: 'Takeout_Box.png',
        cost: 175,
        description: '',
    },
    {
        name: `Tea of Mercy`,
        img: 'Tea_of_Mercy.png',
        cost: 150,
        description: '',
    },
    {
        name: `Thesis on Defense`,
        img: 'Thesis_on_Defense.png',
        cost: 150,
        description: '',
    },
    {
        name: `Three Gorges Bulwark`,
        img: 'Three_Gorges_Bulwark.png',
        cost: 125,
        description: '',
    },
    {
        name: `Tracking Suit`,
        img: 'Tracking_Suit.png',
        cost: 150,
        description: '',
    },
    {
        name: `Vampire's Eyeglasses`,
        img: 'Vampires_Eyeglasses.png',
        cost: 150,
        description: '',
    },
    {
        name: `Water Cushion`,
        img: 'Water_Cushion.png',
        cost: 150,
        description: '',
    },
    {
        name: `Wings of Icarus`,
        img: 'Wings_of_Icarus.png',
        cost: 200,
        description: '',
    }
]

let doctorRelics = [
    {
        name: `Catalystic Tonic`,
        img: 'Catalystic_Tonic.png',
        cost: '1 Random Arcana',
        description: '',
    },
    {
        name: `Critical Placebos`,
        img: 'Critical_Placebos.png',
        cost: '1 Random Arcana',
        description: '',
    },
    {
        name: `Elixir of Might`,
        img: 'Elixir_of_Might.png',
        cost: '1 Random Arcana',
        description: '',
    },
    {
        name: `Health Care Card`,
        img: 'Health_Care_Card.png',
        cost: '1 Random Arcana',
        description: '',
    },
    {
        name: `Messy Prescription`,
        img: 'Messy_Prescription.png',
        cost: '1 Random Arcana',
        description: '',
    },
    {
        name: `Prescription Bottle`,
        img: 'Prescription_Bottle.png',
        cost: '1 Random Arcana',
        description: '',
    },
    {
        name: `Renewing Potion Vial`,
        img: 'Renewing_Potion_Vial.png',
        cost: '1 Random Arcana',
        description: '',
    }
]

let cursedRelics = [
    {
        name: `Aberrant Deck`,
        img: 'Aberrant_Deck.png',
        cost: 25,
        description: '',
    },
    {
        name: `Abhorrent Cologne`,
        img: 'Abhorrent_Cologne.png',
        cost: 25,
        description: '',
    },
    {
        name: `Adorable Mimic`,
        img: 'Adorable_Mimic.png',
        cost: 25,
        description: '',
    },
    {
        name: `Alchemist's Stone`,
        img: 'Alchemists_Stone.png',
        cost: 25,
        description: '',
    },
    {
        name: `Anchor of Burden`,
        img: 'Anchor_of_Burden.png',
        cost: 25,
        description: '',
    },
    {
        name: `Armor of Greed`,
        img: 'Armor_of_Greed.png',
        cost: 25,
        description: '',
    },
    {
        name: `Bewitching Glue`,
        img: 'Bewitching_Glue.png',
        cost: 25,
        description: '',
    },
    {
        name: `Blinding Binoculars`,
        img: 'Blinding_Binoculars.png',
        cost: 25,
        description: '',
    },
    {
        name: `Broken Plague Flask`,
        img: 'Broken_Plague_Flask.png',
        cost: 25,
        description: '',
    },
    {
        name: `Catastrophic Codex`,
        img: 'Catastrophic_Codex.png',
        cost: 25,
        description: '',
    },
    {
        name: `Chaotic Pendulum`,
        img: 'Chaotic_Pendulum.png',
        cost: 25,
        description: '',
    },
    {
        name: `Conga Drum Set`,
        img: 'Conga_Drum_Set.png',
        cost: 25,
        description: '',
    },
    {
        name: `Cracked Sapphire Key`,
        img: 'Cracked_Sapphire_Key.png',
        cost: 25,
        description: '',
    },
    {
        name: `Crimson Clover`,
        img: 'Crimson_Clover.png',
        cost: 25,
        description: '',
    },
    {
        name: `Cruel Chess Clock`,
        img: 'Cruel_Chess_Clock.png',
        cost: 25,
        description: '',
    },
    {
        name: `Curse of the Forager`,
        img: 'Curse_of_the_Forager.png',
        cost: 25,
        description: '',
    },
    {
        name: `Death's Scythe`,
        img: 'Deaths_Scythe.png',
        cost: 25,
        description: '',
    },
    {
        name: `Double Edged Cestus`,
        img: 'Double_Edged_Cestus.png',
        cost: 25,
        description: '',
    },
    {
        name: `Double Toil`,
        img: 'Double_Toil.png',
        cost: 25,
        description: '',
    },
    {
        name: `Double Trouble`,
        img: 'Double_Trouble.png',
        cost: 25,
        description: '',
    },
    {
        name: `Fatal Firecrackers`,
        img: 'Fatal_Firecrackers.png',
        cost: 25,
        description: '',
    },
    {
        name: `Flashy Boots`,
        img: 'Flashy_Boots.png',
        cost: 25,
        description: '',
    },
    {
        name: `Glass Cannon`,
        img: 'Glass_Cannon.png',
        cost: 25,
        description: '',
    },
    {
        name: `Glove of Patience`,
        img: 'Glove_of_Patience.png',
        cost: 25,
        description: '',
    },
    {
        name: `Golden Armor of Envy`,
        img: 'Golden_Armor_of_Envy.png',
        cost: 25,
        description: '',
    },
    {
        name: `Golden Contract`,
        img: 'Golden_Contract.png',
        cost: 25,
        description: '',
    },
    {
        name: `Golden Saber of Envy`,
        img: 'Golden_Saber_of_Envy.png',
        cost: 25,
        description: '',
    },
    {
        name: `Graduation Bouquet`,
        img: 'Graduation_Bouquet.png',
        cost: 25,
        description: '',
    },
    {
        name: `Heartrender's Amulet`,
        img: 'Heartrenders_Amulet.png',
        cost: 25,
        description: '',
    },
    {
        name: `Horned Halo`,
        img: 'Horned_Halo.png',
        cost: 25,
        description: '',
    },
    {
        name: `Jak's Ocarina`,
        img: 'Jaks_Ocarina.png',
        cost: 25,
        description: '',
    },
    {
        name: `Jeremiah's Needle`,
        img: 'Jeremiahs_Needle.png',
        cost: 25,
        description: '',
    },
    {
        name: `Kugo's Stopwatch`,
        img: 'Kugos_Stopwatch.png',
        cost: 25,
        description: '',
    },
    {
        name: `Large Red Button`,
        img: 'Large_Red_Button.png',
        cost: 25,
        description: '',
    },
    {
        name: `Lastborn's Gauntlet`,
        img: 'Lastborns_Gauntlet.png',
        cost: 25,
        description: '',
    },
    {
        name: `Luxury Handbag`,
        img: 'Luxury_Handbag.png',
        cost: 25,
        description: '',
    },
    {
        name: `Magician's Wand`,
        img: 'Magicians_Wand.png',
        cost: 25,
        description: '',
    },
    {
        name: `Makeshift Bridge`,
        img: 'Makeshift_Bridge.png',
        cost: 25,
        description: '',
    },
    {
        name: `Melting Pot`,
        img: 'Melting_Pot.png',
        cost: 25,
        description: '',
    },
    {
        name: `Mercenary's Dagger`,
        img: 'Mercenaries_Dagger.png',
        cost: 25,
        description: '',
    },
    {
        name: `Mystic Sage's Memoir`,
        img: 'Mystic_Sages_Memoir.png',
        cost: 25,
        description: '',
    },
    {
        name: `Nog's Heavenly Boots`,
        img: 'Nogs_Heavenly_Boots.png',
        cost: 25,
        description: '',
    },
    {
        name: `Nox's Cloak`,
        img: 'Noxs_Cloak.png',
        cost: 25,
        description: '',
    },
    {
        name: `Ominous Loan Note`,
        img: 'Ominous_Loan_Note.png',
        cost: 25,
        description: '',
    },
    {
        name: `Overpriced Insurance`,
        img: 'Overpriced_Insurance.png',
        cost: 25,
        description: '',
    },
    {
        name: `Oversized Needle`,
        img: 'Oversized_Needle.png',
        cost: 25,
        description: '',
    },
    {
        name: `Paronomasicon`,
        img: 'Paronomasicon.png',
        cost: 25,
        description: '',
    },
    {
        name: `Pewter Bracelet`,
        img: 'Pewter_Bracelet.png',
        cost: 25,
        description: '',
    },
    {
        name: `Pie of Five Fruits`,
        img: 'Pie_of_Five_Fruits.png',
        cost: 25,
        description: '',
    },
    {
        name: `Quantum Capacitor`,
        img: 'Quantum_Capacitor.png',
        cost: 25,
        description: '',
    },
    {
        name: `Retro Floor Plan`,
        img: 'Retro_Floor_Plan.png',
        cost: 25,
        description: '',
    },
    {
        name: `Rulebook of Thieves`,
        img: 'Rulebook_of_Thieves.png',
        cost: 25,
        description: '',
    },
    {
        name: `Rules of Contingency`,
        img: 'Rules_of_Contingency.png',
        cost: 25,
        description: '',
    },
    {
        name: `Sharpened Stylus`,
        img: 'Sharpened_Stylus.png',
        cost: 25,
        description: '',
    },
    {
        name: `Silver Spinning Top`,
        img: 'Silver_Spinning_Top.png',
        cost: 25,
        description: '',
    },
    {
        name: `Spiked Emergency Kit`,
        img: 'Spiked_Emergency_Kit.png',
        cost: 25,
        description: '',
    },
    {
        name: `Stealthy Haladie`,
        img: 'Stealthy_Haladie.png',
        cost: 25,
        description: '',
    },
    {
        name: `Strongman's Hammer`,
        img: 'Strongmans_Hammer.png',
        cost: 25,
        description: '',
    },
    {
        name: `Tattered Scroll`,
        img: 'Tattered_Scroll.png',
        cost: 25,
        description: '',
    },
    {
        name: `Tiny Crocodile Heart`,
        img: 'Tiny_Crocodile_Heart.png',
        cost: 25,
        description: '',
    },
    {
        name: `Tipsy Gladius`,
        img: 'Tipsy_Gladius.png',
        cost: 25,
        description: '',
    },
    {
        name: `Titan's Equilibrium`,
        img: 'Titans_Equilibrium.png',
        cost: 25,
        description: '',
    },
    {
        name: `Tortoise Shield`,
        img: 'Tortoise_Shield.png',
        cost: 25,
        description: '',
    },
    {
        name: `Vampire's Fangs`,
        img: 'Vampires_Fangs.png',
        cost: 25,
        description: '',
    },
    {
        name: `Volatile Gemstone`,
        img: 'Volatile_Gemstone.png',
        cost: 25,
        description: '',
    },
    {
        name: `Wallet of Splendor`,
        img: 'Wallet_of_Splendor.png',
        cost: 25,
        description: '',
    }
]